Header and TailwindCSS Added
Galabov93/BrokerPlatformFrontEnd pull request #16
Opened 2021-11-11 15:03 UTC by niksfred

TailwindCSS used to style some components. Header added to replace the old menu. Material UI Grid changed with CSS Grid styling.

2021-11-11 21:22 UTC, Galabov93 requested changes
Overall the code and the functionality are great. Well done!

There are some small things to look at. Additionally to the GitHub comments, there are a couple of more style recommendations :
1. The loading spinner is not centered:
![image](https://user-images.githubusercontent.com/12229385/141370207-d56881dd-4419-4d66-9883-d29071338440.png)
2. Plese change the Tippy placement to "auto-start"

2021-11-11 21:22 UTC, Galabov93 commented on src/components/Header/index.js
> +        inActive: "text-xl text-white bg-opacity-90 my-2 px-2 py-1 rounded-md transform hover:bg-white hover:bg-opacity-90 hover:text-blue-500"
This is the normal state of the link, so the class can be called like that
```suggestion
        link: "text-xl text-white bg-opacity-90 my-2 px-2 py-1 rounded-md transform hover:bg-white hover:bg-opacity-90 hover:text-blue-500"
```

2021-11-11 21:22 UTC, Galabov93 commented on src/components/Header/index.js
> +        active: "text-xl bg-white text-blue-500 bg-opacity-90 my-2 px-2 py-1 rounded-md",
```suggestion
        link-active: "text-xl bg-white text-blue-500 bg-opacity-90 my-2 px-2 py-1 rounded-md",
```

2021-11-11 21:22 UTC, Galabov93 commented on src/components/Header/index.js
> +        if (mobileOpen){
This can be simplified to one call:
`setMobileOpen(!isMobileOpen)`
And the boolean values is good to prepended with 'is' or 'has':
https://dev.to/michi/tips-on-naming-boolean-variables-cleaner-code-35ig

2021-11-11 21:22 UTC, Galabov93 commented on src/components/Header/index.js
> +            setmobileOpen(false)
```suggestion
            setMobileOpen(false)
```

2021-11-11 21:22 UTC, Galabov93 commented on src/components/Header/index.js
> +                <CompanyName name="Refer+" classes="flex items-center px-4 py-2 text-2xl text-white" />
```suggestion
                <CompanyLogo name="Refer+" classes="flex items-center px-4 py-2 text-2xl text-white" />
```

2021-11-11 21:22 UTC, Galabov93 commented on src/components/Header/index.js
> +                    <svg xmlns="http://www.w3.org/2000/svg" class="h-12 w-12 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
Export this svg in a separate component with some explanatory name and import it as a component.

2021-11-11 21:22 UTC, Galabov93 commented on src/components/RealEstatesFilter/index.js
>    console.log("RealEstateFilters -> currentFilters", currentFilters);
Remove log

2021-11-11 21:22 UTC, Galabov93 commented on src/pages/RealEstates/index.js
> +  const LIMIT = (1536 > window.innerWidth && window.innerWidth > 1280) ? 21 : 20;
```suggestion
  const LIMIT = (window.innerWidth < 1536  && window.innerWidth > 1280) ? 21 : 20;
```

2021-11-12 08:00 UTC, niksfred commented on src/components/Header/index.js
> +            <img className="h-16" src={require('../../logoRefer.png')} alt="logo" />
Thank you. Noted and edited.

2021-11-12 08:01 UTC, niksfred commented on src/components/Header/index.js
> +        inActive: "text-xl text-white bg-opacity-90 my-2 px-2 py-1 rounded-md transform hover:bg-white hover:bg-opacity-90 hover:text-blue-500"
Changed.

2021-11-12 08:02 UTC, niksfred commented on src/components/Header/index.js
> +        active: "text-xl bg-white text-blue-500 bg-opacity-90 my-2 px-2 py-1 rounded-md",
link-active is unavailable. Changed to linkActive instead.

2021-11-12 08:04 UTC, niksfred commented on src/components/Header/index.js
> +        if (mobileOpen){
Noted. Did not think of that.

2021-11-12 08:05 UTC, niksfred commented on src/components/Header/index.js
> +            setmobileOpen(false)
Changed.

2021-11-12 08:05 UTC, niksfred commented on src/components/Header/index.js
> +                <CompanyName name="Refer+" classes="flex items-center px-4 py-2 text-2xl text-white" />
Changed.

2021-11-12 08:07 UTC, niksfred commented on src/components/Header/index.js
> +                    <svg xmlns="http://www.w3.org/2000/svg" class="h-12 w-12 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
Exported into HamburgerIcon.

2021-11-12 08:07 UTC, niksfred commented on src/components/RealEstatesFilter/index.js
>    console.log("RealEstateFilters -> currentFilters", currentFilters);
Removed.

2021-11-12 08:08 UTC, niksfred commented on src/pages/RealEstates/index.js
> +  const LIMIT = (1536 > window.innerWidth && window.innerWidth > 1280) ? 21 : 20;
Changed. Is this the proper structure for these conditional statements?

2021-11-12 08:41 UTC, Galabov93 commented on src/pages/RealEstates/index.js
> +  const LIMIT = (1536 > window.innerWidth && window.innerWidth > 1280) ? 21 : 20;
Yes, the variable should always be on the left side of the expression.

2021-11-12 13:49 UTC, Galabov93 reviewed
There are a couple of more mobile style issues:
![image](https://user-images.githubusercontent.com/12229385/141477157-af9b6ae6-cc4e-487f-8aba-1c6787a0bdb1.png)
![image](https://user-images.githubusercontent.com/12229385/141477259-86d9f7f8-ce4f-4acb-9e53-4b8dc2b892d0.png)

2021-11-12 15:47 UTC, niksfred commented
![image](https://user-images.githubusercontent.com/77442895/141494134-95316126-0b9e-4c02-a4af-6d2fdbca2d21.png)

Tablet mode seems to be okay on my side. We should investigate the reason in differences.

Mobile needs some finishing indeed, I guess the Tippy  box could be the reason .Will investigate that.

2021-11-14 09:38 UTC, Galabov93 commented
@niksfred Looks good on my side now for mobile and tablet. Thank you!
One last thing before we merge this:
Please add `flex-wrap: wrap;` to the .pagination component on mobile, because it goes out of the screen at the moment:
![image](https://user-images.githubusercontent.com/12229385/141675623-1c9f5e6a-ee48-4726-87ce-15845da30454.png)
Also on the Grid container element for the real estate on mobile, it has padding 2rem, please use 1rem instead, it will look better.

2021-11-14 20:12 UTC, niksfred commented
Everything should be okay now. Flex-wrap added and padding made smaller for "sm" .

2021-11-14 21:03 UTC, Galabov93 approved these changes

2021-11-14 21:04 UTC, merged