Clients
Galabov93/BrokerPlatformFrontEnd pull request #18
Opened 2021-11-17 21:35 UTC by niksfred

POST request implemented for creating client in the database and GET request to retrieve data about all the clients.

2021-11-18 07:39 UTC, Galabov93 requested changes
@niksfred Well done. That's a lot of work done.
There are some things to take a look at
1. Extract and re-use some functions
2. Make use of react-query

2021-11-18 07:39 UTC, Galabov93 commented on src/pages/Clients/index.js
> +const parseJwt = (token) => {
Please export this function from a separate file. You can create a folder for util functions like this one and put the file there like so:  `src/lib/parseJwt` and re-use it in both places

2021-11-18 07:39 UTC, Galabov93 commented on src/pages/Clients/index.js
> +              onSubmit={async (values) => {
Please extract the onSubmit function in a separate method in this component.

2021-11-18 07:39 UTC, Galabov93 commented on src/pages/Clients/index.js
> +                try {
PLease export the post request in  a separate function.

2021-11-18 07:39 UTC, Galabov93 commented on src/pages/Clients/index.js
> +    async function fetchClients() {
Please export this function in api.js

2021-11-18 07:39 UTC, Galabov93 commented on uninstall
> +mysql  Ver 8.0.27-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))
Please remove this file as it it is not related with the project.

2021-11-18 07:39 UTC, Galabov93 commented on src/pages/Clients/index.js
> +    async function fetchClients() {
Also please look into react-query and try to apply it for this get request.

2021-11-18 07:39 UTC, Galabov93 commented on src/pages/Clients/index.js
> +  const [showForm, setShowForm] = useState(false);
Please name the boleans to start with 'is' or 'has', so please rename this to something like this.
```suggestion
  const [isFormShowing, setShowForm] = useState(false);
```

2021-11-18 07:39 UTC, Galabov93 commented on src/pages/Clients/index.js
> +                const realEstatesConstructionType =
Please do the mapping in separate function as well.

2021-11-18 07:39 UTC, Galabov93 commented on src/pages/Clients/index.js
> +  // offerTypes,
?

2021-11-18 14:36 UTC, niksfred commented on src/pages/Clients/index.js
> +const parseJwt = (token) => {
parseJwt function exported into utils folder inside src.

2021-11-18 14:58 UTC, niksfred commented on src/pages/Clients/index.js
> +              onSubmit={async (values) => {
Extracted as separate function inside the component.

2021-11-18 15:01 UTC, niksfred commented on uninstall
> +mysql  Ver 8.0.27-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))
Removed.

2021-11-18 15:02 UTC, niksfred commented on src/pages/Clients/index.js
> +  // offerTypes,
Removed. I thought it would be needed for the clients information and left it unintentionally.

2021-11-18 15:06 UTC, niksfred commented on src/pages/Clients/index.js
> +  const [showForm, setShowForm] = useState(false);
Changed to the one proposed.

2021-11-18 17:13 UTC, Galabov93 requested changes

2021-11-18 17:13 UTC, Galabov93 commented on src/pages/Clients/index.js
> +  const handlePost = async (values) => {
Event handler function names should point to the event 
```suggestion
  const handleSubmit= async (values) => {
```

2021-11-18 17:13 UTC, Galabov93 commented on src/pages/Clients/index.js
> +    const realEstatesConstructionType = values.realEstatesConstructionType
Create a function like this:
`function mapClientValues(values){}` that basically does this transformations:
```
const realEstatesConstructionType = values.realEstatesConstructionType
      .map((el) => {
        return el.value;
      })
      .join(", ");

    const realEstatesNeighborhood = values.realEstatesNeighborhood
      .map((el) => {
        return el.value;
      })
      .join(", ");
```
and returns mappedValues.

2021-11-18 17:13 UTC, Galabov93 commented on src/pages/Clients/index.js
> +    setNewClientData({
Then this call here becomes like this:
```suggestion
    setNewClientData(mappedValues)
```

2021-11-18 17:13 UTC, Galabov93 commented on src/pages/Clients/index.js
> +    try {
The whole try/catch should be coming from another file store in the folder src/api/clients.js and it should export a function called `createNewClient(mappedValues, userId)`

2021-11-18 17:13 UTC, Galabov93 commented on src/utils/FormHelpers/form-data.js
> +export const offerTypes = [
👍

2021-11-18 18:51 UTC, niksfred commented on src/pages/Clients/index.js
> +  const handlePost = async (values) => {
Noted. The reason behind naming the function different than handleSubmit was related to that I did find it duplicating to name it that way after we already have a handleSubmit coming from Formik.

2021-11-18 19:15 UTC, niksfred commented on src/pages/Clients/index.js
> +    setNewClientData({
Done.

2021-11-18 19:15 UTC, niksfred commented on src/pages/Clients/index.js
> +    const realEstatesConstructionType = values.realEstatesConstructionType
Function added.

2021-11-18 19:26 UTC, niksfred commented on src/pages/Clients/index.js
> +    try {
Exported as well. To be hones at this point, the whole component needs to be edited, because even I am becoming lost in it.

2021-11-18 22:07 UTC, Galabov93 requested changes
We are almost ready with this one. Just a few things left to do.

2021-11-18 22:07 UTC, Galabov93 commented on src/utils/CreateNewClient/index.js
> +export async function CreateNewClient({
```suggestion
export async function createNewClient({
```

2021-11-18 22:07 UTC, Galabov93 commented on src/utils/CreateNewClient/index.js
> +    setClientsData([...clientsData, newClient.data]);
```suggestion
   return newClient;
```

2021-11-18 22:07 UTC, Galabov93 commented on src/utils/CreateNewClient/index.js
> +    console.log("error posting note", e);
```suggestion
    console.log("error creating client", e);
```

2021-11-18 22:07 UTC, Galabov93 commented on src/utils/CreateNewClient/index.js
> +import axios from "../../config/API";
This file should be in src/lib/clients.js

2021-11-18 22:07 UTC, Galabov93 commented on src/pages/Clients/index.js
> +    CreateNewClient({ newClientData, setClientsData, clientsData });
```suggestion
    const newClient = await createNewClient(formData);
    setClientsData([...clientsData, newClient])
```

2021-11-18 22:07 UTC, Galabov93 commented on src/pages/Clients/index.js
> +    setNewClientData(mapValues(values, userId));
Here you can just use a new constant, because this is information is not used outside of the function
```suggestion
    const mappedData = mapValues(values, userId));
```

2021-11-18 22:07 UTC, Galabov93 commented on src/pages/Clients/index.js
> +  function mapClientData(data) {
You can move mapClientData and mapValues in a file file helpers.js located in the same folder /src/pages/Clients

2021-11-19 09:19 UTC, niksfred commented on src/utils/CreateNewClient/index.js
> +import axios from "../../config/API";
I am sorry, but I do not understand why this needs to be in a separate file, if we are using the same baseURL.

2021-11-19 17:18 UTC, Galabov93 approved these changes
Well done!!!

2021-11-19 17:19 UTC, merged